config/routes.rb
Alliumtest::Application.routes.draw do
  resources :onion_groups

  resources :root_register_executions

  resources :register_executions

  resources :roots

  resources :onions

  resources :analyses

  resources :analysis_executions

  get "/register_executions/register/:analysis_execution_id" => "register_executions#register" , :as => "register"

  get "/register_executions/get_onions_by_group/:id" => "register_executions#get_onions_by_group"

  get "/register_executions/get_group_by_analysis/:id" => "register_executions#get_group_by_analysis"

  get "/register_executions/report/:onion_id" => "register_executions#report", :as => "report"

  get "/register_executions/report_group/:group_id" => "register_executions#report_group", :as => "report_group"

  get "/analysis_executions/get_onions_from_analysis/:id" => "analysis_executions#get_onions_from_analysis"

  root to: "analyses#index" , :as => "index"

  

end

app/models/register_execution.rb
class RegisterExecution < ActiveRecord::Base

  attr_accessor :analysis_name, :onion_group_id, :analysis_id, :day, :onion_id_graphic

  has_one :onion
  belongs_to :analysis_execution

  validates_presence_of :root_size, :day_number, :onion_id

  def get_root_size(register_execution_id)
    root_id = RootRegisterExecution.find_by_register_execution_id(register_execution_id).root_id
    Root.find_by_id(root_id).size
  end

end

app/controllers/register_executions_controller.rb
class RegisterExecutionsController < ApplicationController
  before_action :set_register_execution, only: [:show, :edit, :update, :destroy]

  # GET /register_executions
  # GET /register_executions.json
  def index
    # @register_executions = RegisterExecution.all(:order_by => 'allium_cepa_id')
    @register_executions = RegisterExecution.all.order( :day_number , onion_id: :asc)
    @register_execution = RegisterExecution.new
    @days = []
    @onion = Onion.new
  end

  # GET /register_executions/1
  # GET /register_executions/1.json
  def show
  end

  # GET /register_executions/new
  def new
    @register_execution = RegisterExecution.new
  end

  # GET /register_executions/1/edit
  def edit
  end

  # POST /register_executions
  # POST /register_executions.json
  def create
    @register_execution = RegisterExecution.new(register_execution_params)

    respond_to do |format|
      if @register_execution.save

        root = Root.new
        root.size =  register_execution_params['root_size']
        root.onion_id = register_execution_params['onion_id']
        if root.save
          root_register_execution = RootRegisterExecution.new
          root_register_execution.register_execution_id =  @register_execution.id
          root_register_execution.root_id = root.id
          root_register_execution.save
        end

        format.html { redirect_to @register_execution, notice: 'Register execution was successfully created.' }
        format.json { render action: 'show', status: :created, location: @register_execution }
      else

        register_execution = params[:register_execution]
        analysis_execution = AnalysisExecution.find_by_id(register_execution['analysis_execution_id'])
        #analysis = Analysis.find_by_id(analysis_execution.analysis.id)
        analysis = Analysis.find_by_id(register_execution[:analysis_id])

        @analysis_execution_id = analysis_execution.id
        @analysis_id =  analysis.id
        @analysis_name = analysis.name
        @groups = OnionGroup.where(:analysis_id => analysis.id)
        @onions = [] #Onion.find_all_by_analysis_id()

        format.html { render action: 'new' }
        format.json { render json: @register_execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /register_executions/1
  # PATCH/PUT /register_executions/1.json
  def update
    respond_to do |format|
      if @register_execution.update(register_execution_params)
        format.html { redirect_to @register_execution, notice: 'Register execution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @register_execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /register_executions/1
  # DELETE /register_executions/1.json
  def destroy
    @register_execution.destroy
    respond_to do |format|
      format.html { redirect_to register_executions_url }
      format.json { head :no_content }
    end
  end

  def register
    @register_execution = RegisterExecution.new
    analysis_execution = AnalysisExecution.find_by_id(params[:analysis_execution_id])
    analysis = Analysis.find_by_id(analysis_execution.analysis.id)

    @analysis_execution_id = analysis_execution.id
    @analysis_id =  analysis.id
    @analysis_name = analysis.name
    @groups = OnionGroup.where(:analysis_id => analysis.id)
    @onions = [] #Onion.find_all_by_analysis_id()

    render 'new'
  end

  def get_onions_by_group
    @onions = Onion.where(:onion_group_id => params[:id])
    render :json => @onions.map{|c| [c.id, c.name]}
  end

  def get_group_by_analysis
    @groups = OnionGroup.where(:analysis_id => params[:id])
    render :json => @groups.map{|c| [c.id, c.name]}
  end

  def report
    @register_execution = RegisterExecution.new
    @onion = Onion.find_by_id(params[:onion_id])
    @days = RegisterExecution.all.where(:onion_id => @onion.id).map{ |re| re.day_number }.uniq
    @register_executions = RegisterExecution.all.where(:onion_id => @onion.id).order( :day_number , onion_id: :asc)
  end

  def report_group
    @register_execution = RegisterExecution.new
    @days = RegisterExecution.all.map{ |re| re.day_number }.uniq
    @onion_group = OnionGroup.find_by_id(params[:group_id])
    onions_group = Onion.where(:onion_group_id => @onion_group.id)

    @onions = RegisterExecution.all.where(:onion_id => onions_group).map { |re| re.onion_id }.uniq

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register_execution
      @register_execution = RegisterExecution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_execution_params
      params.require(:register_execution).permit(:day_number, :analysis_execution_id, :onion_id, :root_size)
    end
end

app/helpers/register_executions_helper.rb
module RegisterExecutionsHelper

  def get_avg_by_day_number_and_onion_id(day_number, onion_id)
    avg = RegisterExecution.all.where(:onion_id => onion_id, :day_number => day_number).map { |re| re.root_size }.reduce(:+).to_f / RegisterExecution
    .all
    .where(:onion_id  => onion_id, :day_number => day_number).size
    if avg.nan?
      0
    else
      avg
    end
  end

end

app/views/register_executions/_filter_graphic_onion.erb
<fieldset>
  <legend>Allium Cepa para gráfico</legend>
<%= simple_form_for @register_execution, :html => {:class => 'form-horizontal'} do |f| %>

    <%= f.input :analysis_id, label: 'Análise', collection: Analysis.all,
                prompt: "Selecione a Análise" %>
    <%= f.input :onion_group_id, label: 'Grupo', collection: [],
                prompt: "Selecione o Grupo" %>
    <%= f.input :onion_id, label: 'Allium Cepa', collection: [],
                prompt: "Selecione a Allium Cepa" %>
    <%= f.input :day, label: 'Dia', collection: @days,
                prompt: "Selecione um dia" %>

    <a id='btn_graphic' href="#">Visualizar gráfico</a>
      |
    <a id='btn_graphic_group' href="#">Visualizar gráfico por grupo</a>

<% end %>
</fieldset>

app/views/register_executions/_form.html.erb
<%= simple_form_for @register_execution, :html => {:class => 'form-horizontal'} do |f| %>

    <%= f.hidden_field :analysis_execution_id, value: @analysis_execution_id %>
    <%= f.hidden_field :analysis_id, value: @analysis_id %>
    <%= f.input :analysis_name, disabled: true, label: 'Execução da analise', :input_html => {:value => @analysis_name} %>
    <%= f.input :day_number, label: 'Dia' %>
    <%= f.input :onion_group_id, label: 'Grupo', collection: @groups,
                prompt: "Selecione o Grupo" %>
    <%= f.input :onion_id, label: 'Allium Cepa', collection: @onions,
                prompt: "Selecione a Allium Cepa" %>
    <%= f.input :root_size, as: :decimal ,  label: 'Tamanho da raiz' %>

    <div class="form-actions">
      <%= f.submit 'Registrar', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  register_executions_path, :class => 'btn' %>
    </div>
<% end %>

app/views/register_executions/edit.html.erb
<%- model_class = RegisterExecution -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/register_executions/index.html.erb
<%- model_class = RegisterExecution -%>
<div class="page-header">
  <h1>Registro diário das execuções</h1>
</div>

<%= render :partial => 'filter_graphic_onion' %>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Dia</th>
    <th>Analise</th>
    <th>Allium Cepa</th>
    <th>Tamanho da raiz</th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @register_executions.each do |register_execution| %>
      <tr>
        <td><%= register_execution.day_number %></td>
        <td><%= register_execution.analysis_execution.analysis.name %></td>
        <td><%= Onion.find_by_id(register_execution.onion_id).name %></td>
        <td><%= register_execution.get_root_size(register_execution.id).to_f %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      register_execution_path(register_execution),
                      :method => :delete,
                      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_register_execution_path,
            :class => 'btn btn-primary' %>

app/views/register_executions/new.html.erb
<%- model_class = RegisterExecution -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/register_executions/report.html.erb
<div class="page-header">
  <h1>Registro diário das execuções</h1>
</div>
<script type="text/javascript" charset="utf-8">
    $(function () {
        new Highcharts.Chart({
            chart: { renderTo: 'register_chart' },
            title: { text: 'Registros por Dia' },
            xAxis: {
                categories:<%= @days.inspect  %>
            },
            yAxis: {
                title: { text: 'Tamanho da Raiz', type: 'decimal'}
            },
            series: [

                {
                    name: "<%= @onion.name %>",
                    data: [
                        <% @days.select{ |day| %>
                        <%= get_avg_by_day_number_and_onion_id(day, @onion.id)   %>,
                        <% }.uniq %>
                    ]
                 }
                ]
        });
    });
</script>

<%= render :partial => 'filter_graphic_onion' %>

<div id='register_chart' style="width: 100%; height: 300px"></div>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Dia</th>
    <th>Analise</th>
    <th>Allium Cepa</th>
    <th>Tamanho da raiz</th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @register_executions.each do |register_execution| %>
      <tr>
        <td><%= register_execution.day_number %></td>
        <td><%= register_execution.analysis_execution.analysis.name %></td>
        <td><%= Onion.find_by_id(register_execution.onion_id).name %></td>
        <td><%= get_avg_by_day_number_and_onion_id(register_execution.day_number, register_execution.onion_id) %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      register_execution_path(register_execution),
                      :method => :delete,
                      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_register_execution_path,
            :class => 'btn btn-primary' %>

app/views/register_executions/report_group.html.erb
<div class="page-header">
  <h1>Registro diário das execuções</h1>
</div>
<script type="text/javascript" charset="utf-8">
    $(function () {
        new Highcharts.Chart({
            chart: {
                type: 'column',
                renderTo: 'container'
            },
            title: {
                text: '<%= "Grupo #{@onion_group.name}" %>'
            },
            subtitle: {
                text: '<%= "#{@onion_group.description}" %>'
            },
            xAxis: {
                categories: <%= @days.inspect %>
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Média de crescimento'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                        '<td style="padding:0"><b>{point.y:.1f} cm</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series:
            [
              <% @onions.select { |onion_id| %>
              {
                name: "<%= Onion.find_by_id(onion_id).name %>",
                data:
                [
                    <% @days.select{ |day|   %>
                      <%= get_avg_by_day_number_and_onion_id(day, onion_id)   %>,
                    <% } %>
                ]
              },
              <% } %>
            ]
        });
    });
</script>

<%= render :partial => 'filter_graphic_onion' %>

<div id='container' style="width: 100%; height: 300px"></div>

app/views/register_executions/show.html.erb
<div class="page-header">
  <h1>Registro do dia #<%= @register_execution.day_number %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Analise:</strong></dt>
  <dd><%= @register_execution.analysis_execution.analysis.name %></dd>
  <dt>Allium cepa: </strong> </dt>
  <dd><%= Onion.find_by_id(@register_execution.onion_id).name %></dd>
  <dt>Tamanho da raiz: </strong> </dt>
  <dd><%= @register_execution.root_size %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              register_executions_path, :class => 'btn'  %>
  <%= link_to 'Registrar Outra',  register_path(@register_execution.analysis_execution.analysis.id), :class => 'btn' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_register_execution_path(@register_execution), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              register_execution_path(@register_execution),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>