config/routes.rb
Alliumtest::Application.routes.draw do
  resources :onion_groups

  resources :root_register_executions

  resources :register_executions

  resources :roots

  resources :onions

  resources :analyses

  resources :analysis_executions

  get "/register_executions/register/:analysis_execution_id" => "register_executions#register" , :as => "register"

  get "/register_executions/get_onions_by_group/:id" => "register_executions#get_onions_by_group"

  get "/register_executions/get_group_by_analysis/:id" => "register_executions#get_group_by_analysis"

  get "/register_executions/report/:onion_id" => "register_executions#report", :as => "report"

  get "/register_executions/report_group/:group_id" => "register_executions#report_group", :as => "report_group"

  get "/analysis_executions/get_onions_from_analysis/:id" => "analysis_executions#get_onions_from_analysis"

  root to: "analyses#index" , :as => "index"

  

end

app/models/onion.rb
class Onion < ActiveRecord::Base

  belongs_to :onion_group
  has_many :roots

  validates_presence_of :description, :name, :onion_group_id

end

app/controllers/onions_controller.rb
class OnionsController < ApplicationController
  before_action :set_onion, only: [:show, :edit, :update, :destroy]

  # GET /onions
  # GET /onions.json
  def index
    @onions = Onion.all
  end

  # GET /onions/1
  # GET /onions/1.json
  def show
  end

  # GET /onions/new
  def new
    @onion = Onion.new
  end

  # GET /onions/1/edit
  def edit
  end

  # POST /onions
  # POST /onions.json
  def create
    @onion = Onion.new(onion_params)

    respond_to do |format|
      if @onion.save
        format.html { redirect_to @onion, notice: 'Onion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @onion }
      else
        format.html { render action: 'new' }
        format.json { render json: @onion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /onions/1
  # PATCH/PUT /onions/1.json
  def update
    respond_to do |format|
      if @onion.update(onion_params)
        format.html { redirect_to @onion, notice: 'Onion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @onion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /onions/1
  # DELETE /onions/1.json
  def destroy
    @onion.destroy
    respond_to do |format|
      format.html { redirect_to onions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_onion
      @onion = Onion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def onion_params
      params.require(:onion).permit(:name, :description, :onion_group_id)
    end
end

app/helpers/onions_helper.rb
module OnionsHelper
end

app/views/onions/_form.html.erb
<%= simple_form_for @onion, :html => {:class => 'form-horizontal'} do |f| %>

    <fieldset>

      <legend>Dados</legend>
      <%= f.input :name, label: 'Nome', as: :string %>
      <%= f.input :description, label: 'Descrição', as: :text %>
      <%= f.association :onion_group, label: 'Grupo', collection: OnionGroup.all(order: 'name'), prompt: "Selecione um grupo" %>

      <div class="form-actions">
        <%= f.submit 'Criar Allium Cepa', :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    onions_path, :class => 'btn' %>
      </div>
    </fieldset>

<% end %>

app/views/onions/edit.html.erb
<%- model_class = Onion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/onions/index.html.erb
<%- model_class = Onion -%>
<div class="page-header">
  <h1>Allium Cepa</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Grupo</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @onions.each do |onion| %>
      <tr>
        <td><%= link_to onion.name, onion_path(onion) %></td>
        <td><%= onion.description %></td>
        <td><%= OnionGroup.find_by_id(onion.onion_group_id).name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_onion_path(onion), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      onion_path(onion),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_onion_path,
            :class => 'btn btn-primary' %>

app/views/onions/new.html.erb
<%- model_class = Onion -%>
<div class="page-header">
  <h1>Criar Allium Cepa</h1>
</div>
<%= render :partial => 'form' %>

app/views/onions/show.html.erb
<%- model_class = Onion -%>
<div class="page-header">
  <h1>Allium Cepa</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Nome:</strong></dt>
  <dd><%= @onion.name %></dd>
  <dt><strong>Descrição:</strong></dt>
  <dd><%= @onion.description %></dd>
  <dt><strong>Grupo:</strong></dt>
  <dd><%= OnionGroup.find_by_id(@onion.onion_group_id).name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              onions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_onion_path(@onion), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              onion_path(@onion),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>