config/routes.rb
Alliumtest::Application.routes.draw do
  resources :onion_groups

  resources :root_register_executions

  resources :register_executions

  resources :roots

  resources :onions

  resources :analyses

  resources :analysis_executions

  get "/register_executions/register/:analysis_execution_id" => "register_executions#register" , :as => "register"

  get "/register_executions/get_onions_by_group/:id" => "register_executions#get_onions_by_group"

  get "/register_executions/get_group_by_analysis/:id" => "register_executions#get_group_by_analysis"

  get "/register_executions/report/:onion_id" => "register_executions#report", :as => "report"

  get "/register_executions/report_group/:group_id" => "register_executions#report_group", :as => "report_group"

  get "/analysis_executions/get_onions_from_analysis/:id" => "analysis_executions#get_onions_from_analysis"

  root to: "analyses#index" , :as => "index"

  

end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
  before_action :set_analysis, only: [:show, :edit, :update, :destroy]

  # GET /analyses
  # GET /analyses.json
  def index
    @analyses = Analysis.all
  end

  # GET /analyses/1
  # GET /analyses/1.json
  def show
  end

  # GET /analyses/new
  def new
    @analysis = Analysis.new
  end

  # GET /analyses/1/edit
  def edit
  end

  # POST /analyses
  # POST /analyses.json
  def create
    @analysis = Analysis.new(analysis_params)

    respond_to do |format|
      if @analysis.save
        format.html { redirect_to @analysis, notice: 'Analysis was successfully created.' }
        format.json { render action: 'show', status: :created, location: @analysis }
      else
        format.html { render action: 'new' }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analyses/1
  # PATCH/PUT /analyses/1.json
  def update
    respond_to do |format|
      if @analysis.update(analysis_params)
        format.html { redirect_to @analysis, notice: 'Analysis was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analyses/1
  # DELETE /analyses/1.json
  def destroy
    @analysis.destroy
    respond_to do |format|
      format.html { redirect_to analyses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analysis
      @analysis = Analysis.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analysis_params
      params.require(:analysis).permit(:name, :start_date, :end_date, :description)
    end
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/views/analyses/_form.html.erb
<%= simple_form_for @analysis, :html => {:class => 'form-horizontal'} do |f| %>

    <fieldset>
      <legend>Dados</legend>

      <%= f.input :name, label: 'Nome' %>
      <%= f.input :description, label: 'Descrição' %>
      <%= f.input :start_date, label: 'Início', as: :string, input_html: { value: f.object.start_date } %>
      <%= f.input :end_date, label: 'Fim', as: :string, input_html: { value: f.object.end_date } %>

      <div class="form-actions">
        <%= f.submit 'Criar Análise', :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => 'Cancelar'),
                    analyses_path, :class => 'btn' %>
      </div>
    </fieldset>
<% end %>

app/views/analyses/edit.html.erb
<%- model_class = Analysis -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/analyses/index.html.erb
<%- model_class = Analysis -%>
<div class="page-header">
  <h1>Analises</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Inicio</th>
      <th>Fim</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @analyses.each do |analysis| %>
      <tr>
        <td><%= link_to analysis.name, analysis_path(analysis) %></td>
        <td><%= analysis.description %></td>
        <td><%= analysis.start_date %></td>
        <td><%= analysis.end_date %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_analysis_path(analysis), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      analysis_path(analysis),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => 'Novo'),
            new_analysis_path,
            :class => 'btn btn-primary' %>

app/views/analyses/new.html.erb
<%- model_class = Analysis -%>
<div class="page-header">
  <h1>Nova Análise</h1>
</div>
<%= render :partial => 'form' %>

app/views/analyses/show.html.erb
<%- model_class = Analysis -%>
<div class="page-header">
  <h1>Análises</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Nome:</strong></dt>
  <dd><%= @analysis.name %></dd>
  <dt><strong>Descrição:</strong></dt>
  <dd><%= @analysis.description %></dd>
  <dt><strong>Início:</strong></dt>
  <dd><%= @analysis.start_date %></dd>
  <dt><strong>Fim:</strong></dt>
  <dd><%= @analysis.end_date %></dd>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              analyses_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_analysis_path(@analysis), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              analysis_path(@analysis),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>