config/routes.rb
Alliumtest::Application.routes.draw do
  resources :onion_groups

  resources :root_register_executions

  resources :register_executions

  resources :roots

  resources :onions

  resources :analyses

  resources :analysis_executions

  get "/register_executions/register/:analysis_execution_id" => "register_executions#register" , :as => "register"

  get "/register_executions/get_onions_by_group/:id" => "register_executions#get_onions_by_group"

  get "/register_executions/get_group_by_analysis/:id" => "register_executions#get_group_by_analysis"

  get "/register_executions/report/:onion_id" => "register_executions#report", :as => "report"

  get "/register_executions/report_group/:group_id" => "register_executions#report_group", :as => "report_group"

  get "/analysis_executions/get_onions_from_analysis/:id" => "analysis_executions#get_onions_from_analysis"

  root to: "analyses#index" , :as => "index"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alliumtest</title>

  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "highcharts" %>

  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">AlliumTest</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Analise", analyses_path %></li>
          <li><%= link_to "Grupos", onion_groups_path %></li>
          <li><%= link_to "Allium Cepa", onions_path %></li>
          <li><%= link_to "Execução", analysis_executions_path  %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class='container'>
  <% flash.each do |name, msg|	%>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class='close' data-dismiss="alert">x</a>
        <%= msg %>
      </div>
  <% end  %>

  <div class='row'>
    <div class='span9'><%= yield %></div>
    <div class='span3'>
      <h2>Sobre o sistema</h2>
      Projeto cientifico destinado ao estudo da <i>Allium Cepa</i>.
      Análises do desenvolvimento das raízes em um determinado período, sobre a ação de reagentes quimicos.
    </div>
  </div>

</div>

</body>
</html>